import { SvgDatabase } from 'app/icons/designSystem/SvgDatabase';
import { SvgInvoice } from 'app/icons/designSystem/SvgInvoice';
import { SvgPackage } from 'app/icons/designSystem/SvgPackage';
import {
  SvgActiu,
  SvgAvarie,
  SvgCustomer,
  SvgGear,
  SvgInspect,
  SvgMenu,
  SvgOperari,
  SvgOrder,
  SvgPanel,
  SvgRecanvi,
  SvgReport,
  SvgReview,
  SvgUsers,
} from 'app/icons/icons';
import { UserPermission, UserType } from 'app/interfaces/User';
import { generateKey, SideNavItem } from 'app/types/SideNavItem';

export const SIDENAV_ITEMS: SideNavItem[] = [
  {
    key: generateKey(),
    titleKey: 'sidebar.dashboard',
    icon: SvgPanel,
    path: '/menu',
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.AdminCRM,
    ],
    userType: [UserType.Maintenance, UserType.Production, UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.preventives',
    path: '',
    permission: [UserPermission.Administrator],
    userType: [UserType.Maintenance],
    submenu: true,
    icon: SvgReview,
    submenuItems: [
      {
        key: generateKey(),
        titleKey: 'sidebar.preventive.config',
        path: '/preventive',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.inspectionPoints',
        path: '/inspectionPoints',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.preventive.calendar',
        path: '/preventive/calendar',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
    ],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.correctives',
    path: '/corrective',
    icon: SvgAvarie,
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.AdminCRM,
    ],
    userType: [UserType.Maintenance, UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.tickets',
    path: '/corrective',
    icon: SvgAvarie,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.workOrders',
    path: '/workOrders',
    icon: SvgOrder,
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.AdminCRM,
    ],
    userType: [UserType.Maintenance, UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.workOrders.historyTickets',
    path: '/workOrders',
    icon: SvgOrder,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.orders',
    path: '',
    permission: [UserPermission.Administrator],
    userType: [UserType.Maintenance, UserType.Warehouse],
    submenu: true,
    icon: SvgReview,
    submenuItems: [
      {
        key: generateKey(),
        titleKey: 'sidebar.orders.purchases',
        path: '/orders/purchases',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.orders.purchases.lowStock',
        path: '/orders/purchases/lowStock',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.orders.deliveries',
        path: '/orders/deliverys',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
    ],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.spareParts',
    path: '/spareParts',
    icon: SvgRecanvi,
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.SpareParts,
      UserPermission.AdminCRM,
    ],
    userType: [UserType.Maintenance, UserType.Warehouse, UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.reports.consumedSpareParts',
    icon: SvgReport,
    path: '/reports/spareParts/consumedSpareParts',
    permission: [UserPermission.Administrator, UserPermission.SpareParts],
    userType: [UserType.Maintenance],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.reports.downtimesReport',
    icon: SvgReport,
    path: '/reports/downtimesReport',
    permission: [UserPermission.Administrator, UserPermission.SpareParts],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.customers',
    icon: SvgCustomer,
    path: '/customer',
    permission: [UserPermission.AdminCRM, UserPermission.AdminCRM],
    userType: [UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.invoices',
    icon: SvgInvoice,
    path: '/invoices',
    permission: [UserPermission.AdminCRM, UserPermission.AdminCRM],
    userType: [UserType.CRM],
  },
  {
    key: generateKey(),
    titleKey: 'sidebar.config',
    path: '',
    permission: [UserPermission.Administrator, UserPermission.AdminCRM],
    userType: [
      UserType.Maintenance,
      UserType.Production,
      UserType.Warehouse,
      UserType.CRM,
    ],
    submenu: true,
    icon: SvgGear,
    submenuItems: [
      {
        key: generateKey(),
        titleKey: 'sidebar.assets',
        path: '/assets',
        icon: SvgActiu,
        permission: [UserPermission.Administrator, UserPermission.AdminCRM],
        userType: [UserType.Maintenance, UserType.Production, UserType.CRM],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.providers',
        path: '/providers',
        icon: SvgPackage,
        permission: [UserPermission.Administrator, UserPermission.AdminCRM],
        userType: [UserType.Maintenance, UserType.Warehouse, UserType.CRM],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.warehouse',
        path: '/wareHouse',
        icon: SvgMenu,
        permission: [UserPermission.Administrator, UserPermission.AdminCRM],
        userType: [UserType.Maintenance, UserType.Warehouse, UserType.CRM],
      },
      /*{
        key: generateKey(),
        title: 'Seccions',
        path: '/section',
        icon: SvgMenu,
        userType: [UserType.Production],
        permission: [UserPermission.Administrator],
      },
      {
        key: generateKey(),
        title: 'Màquines',
        path: '/machines',
        icon: SvgMachine,
        userType: [],
        permission: [],
      },*/
      {
        key: generateKey(),
        titleKey: 'sidebar.accounts',
        path: '/account',
        icon: SvgOperari,
        userType: [UserType.Production, UserType.Maintenance],
        permission: [UserPermission.Administrator],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.operators',
        path: '/operators',
        icon: SvgOperari,
        userType: [UserType.Production, UserType.Maintenance, UserType.CRM],
        permission: [UserPermission.Administrator, UserPermission.AdminCRM],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.users',
        path: '/users',
        icon: SvgUsers,
        userType: [UserType.Production, UserType.Maintenance, UserType.CRM],
        permission: [UserPermission.Administrator, UserPermission.AdminCRM],
      },
      {
        key: generateKey(),
        titleKey: 'sidebar.system',
        path: '/system',
        icon: SvgDatabase,
        userType: [UserType.CRM],
        permission: [UserPermission.AdminCRM],
      },
    ],
  },
];
