import {
  SvgActiu,
  SvgAvarie,
  SvgGear,
  SvgInspect,
  SvgMachine,
  SvgMenu,
  SvgOperari,
  SvgOrder,
  SvgPanel,
  SvgRecanvi,
  SvgReport,
  SvgReview,
  SvgUsers,
} from 'app/icons/icons';
import { UserPermission, UserType } from 'app/interfaces/User';
import { generateKey, SideNavItem } from 'app/types/SideNavItem';

export const SIDENAV_ITEMS: SideNavItem[] = [
  {
    key: generateKey(),
    title: 'Dashboard',
    icon: SvgPanel,
    path: '/menu',
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.AdminCRM,
    ],
    userType: [UserType.Maintenance, UserType.Production, UserType.CRM],
  },
  {
    key: generateKey(),
    title: 'Revisions',
    path: '',
    permission: [UserPermission.Administrator],
    userType: [UserType.Maintenance],
    submenu: true,
    icon: SvgReview,
    submenuItems: [
      {
        key: generateKey(),
        title: 'Configuració',
        path: '/preventive',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
      {
        key: generateKey(),
        title: 'Punts Inspecció',
        path: '/inspectionPoints',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
      {
        key: generateKey(),
        title: 'Calendari',
        path: '/preventive/calendar',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance],
      },
    ],
  },
  {
    key: generateKey(),
    title: 'Avaries',
    path: '/corrective',
    icon: SvgAvarie,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Maintenance],
  },
  {
    key: generateKey(),
    title: 'Tiquets',
    path: '/corrective',
    icon: SvgAvarie,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    title: 'Ordres de treball',
    path: '/workOrders',
    icon: SvgOrder,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Maintenance],
  },
  {
    key: generateKey(),
    title: 'Històric de Tiquets',
    path: '/workOrders',
    icon: SvgOrder,
    permission: [UserPermission.Administrator, UserPermission.Worker],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    title: 'Comandes i Recepcions',
    path: '',
    permission: [UserPermission.Administrator],
    userType: [UserType.Maintenance, UserType.Warehouse],
    submenu: true,
    icon: SvgReview,
    submenuItems: [
      {
        key: generateKey(),
        title: 'Comandes',
        path: '/orders/purchases',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      {
        key: generateKey(),
        title: 'Proposta Automàtica Compra',
        path: '/orders/purchases/lowStock',
        icon: SvgGear,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      {
        key: generateKey(),
        title: 'Recepcions',
        path: '/orders/deliverys',
        icon: SvgInspect,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
    ],
  },
  {
    key: generateKey(),
    title: 'Recanvis',
    path: '/spareParts',
    icon: SvgRecanvi,
    permission: [
      UserPermission.Administrator,
      UserPermission.Worker,
      UserPermission.SpareParts,
    ],
    userType: [UserType.Maintenance, UserType.Warehouse],
  },
  {
    key: generateKey(),
    title: 'Reports',
    icon: SvgReport,
    path: '/reports/spareParts/consumedSpareParts',
    permission: [UserPermission.Administrator, UserPermission.SpareParts],
    userType: [UserType.Maintenance],
  },
  {
    key: generateKey(),
    title: 'Reports',
    icon: SvgReport,
    path: '/reports/downtimesReport',
    permission: [UserPermission.Administrator, UserPermission.SpareParts],
    userType: [UserType.Production],
  },
  {
    key: generateKey(),
    title: 'Clients',
    icon: SvgReport,
    path: '/customer',
    permission: [UserPermission.AdminCRM, UserPermission.AdminCRM],
    userType: [UserType.CRM],
  },
  {
    key: generateKey(),
    title: 'Configuració',
    path: '',
    permission: [UserPermission.Administrator, UserPermission.AdminCRM],
    userType: [
      UserType.Maintenance,
      UserType.Production,
      UserType.Warehouse,
      UserType.CRM,
    ],
    submenu: true,
    icon: SvgGear,
    submenuItems: [
      {
        key: generateKey(),
        title: 'Actius i Equips',
        path: '/assets',
        icon: SvgActiu,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Production],
      },
      {
        key: generateKey(),
        title: 'Proveïdors',
        path: '/providers',
        icon: SvgMenu,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      {
        key: generateKey(),
        title: 'Magatzems',
        path: '/wareHouse',
        icon: SvgMenu,
        permission: [UserPermission.Administrator],
        userType: [UserType.Maintenance, UserType.Warehouse],
      },
      /*{
        key: generateKey(),
        title: 'Seccions',
        path: '/section',
        icon: SvgMenu,
        userType: [UserType.Production],
        permission: [UserPermission.Administrator],
      },
      {
        key: generateKey(),
        title: 'Màquines',
        path: '/machines',
        icon: SvgMachine,
        userType: [],
        permission: [],
      },*/
      {
        key: generateKey(),
        title: 'Sistema',
        path: '/system',
        icon: SvgOperari,
        userType: [UserType.CRM],
        permission: [UserPermission.AdminCRM],
      },
      {
        key: generateKey(),
        title: 'Comptes Comptables',
        path: '/account',
        icon: SvgOperari,
        userType: [UserType.Production, UserType.Maintenance],
        permission: [UserPermission.Administrator],
      },
      {
        key: generateKey(),
        title: 'Operaris',
        path: '/operators',
        icon: SvgOperari,
        userType: [UserType.Production, UserType.Maintenance],
        permission: [UserPermission.Administrator],
      },
      {
        key: generateKey(),
        title: 'Usuaris',
        path: '/users',
        icon: SvgUsers,
        userType: [UserType.Production, UserType.Maintenance],
        permission: [UserPermission.Administrator],
      },
    ],
  },
];
