name: Multitenant Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Client:'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Load client-specific env
      run: cp vercel-configs/${{ github.event.inputs.client }}.env .env

    - name: Deploy to Vercel
      run: |
        # Vincula el proyecto (si no está vinculado)
        vercel link --yes --token ${{ secrets.VERCEL_TOKEN }} --project okron-web
        # Primero cargar las variables de entorno
        vercel env pull .env --token ${{ secrets.VERCEL_TOKEN }} --environment production
        # Luego hacer deploy
        DEPLOYMENT_URL=$(vercel deploy --prod \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --yes \
          --name ${{ github.event.inputs.client }} \
          --confirm)
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV

    - name: Alias domain
      run: |
        vercel alias set ${{ env.DEPLOYMENT_URL }} ${{ github.event.inputs.client }}.vercel.app --token ${{ secrets.VERCEL_TOKEN }}


