name: Multitenant Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Client:'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Load client-specific env
      run: cp vercel-configs/${{ github.event.inputs.client }}.env .env

    - name: Export env variables
      run: |
        set -o allexport
        source .env
        set +o allexport

    - name: Set client-specific env variable inline
      run: |
        if [ "${{ github.event.inputs.client }}" = "jpont" ]; then
          echo "ENV_VARS=--env NEXT_PUBLIC_API_BASE_URL=https://jpontokronapi.azurewebsites.net/api/" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.client }}" = "kolder" ]; then
          echo "ENV_VARS=--env NEXT_PUBLIC_API_BASE_URL=https://kolderapi.azurewebsites.net/api/" >> $GITHUB_ENV
        else
          echo "ENV_VARS=" >> $GITHUB_ENV
        fi

    - name: Deploy to Vercel
      run: |
        # Vincula el proyecto (si no está vinculado)
        vercel link --yes --token ${{ secrets.VERCEL_TOKEN }} --project okron-web
        # Luego hacer deploy
        DEPLOYMENT_URL=$(vercel deploy --prod \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --yes \
          $ENV_VARS \
          --name ${{ github.event.inputs.client }} \
          --confirm)
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV

    - name: Alias domain
      run: |
        vercel alias set ${{ env.DEPLOYMENT_URL }} ${{ github.event.inputs.client }}.vercel.app --token ${{ secrets.VERCEL_TOKEN }}


